first_word_dict = {"dog": "kutya", "cat": "macska", "fish": "hal"}

chinese_0928 = {'bachelor degree (t)': 'ben3ke1',
                'master degree (t)': 'shuo4shi4',
                'sequence, one by one (t)': 'ran3hou4',
                'in that case(t)': 'na4',
                'little girl': 'xiao nu er',
                'your exact age (t)': 'zhou1sui4',
                'nominal age (t)': 'xu1sui4',
                'in my eyes': 'zai wo yan li',
                'how I see': 'zai wo kan lai',
                'to meet': 'jian mian',
                'to see': 'kan dao',
                'lady': 'nushi',
                'plus': 'ling',
                'lonely': 'gudan',
                'holiday (t)': 'fang4jia4',
                'the time when I was 25': 'wo 25 sui de shihou',
                'lively (t)': 're4nao4',
                'welcome you to my home': 'huan ying ni lai wo de jia',
                'definetely (t)': 'yi3ding4',
                'office (t)': 'ban4gong1shi4',
                'dont need to': 'bu yong qu',
                'maths (t)': 'shu4xue2',
                'number (t)': 'shu4',
                'architect': 'fan zi she ji shi',
                'doctor (t)': 'yi1sheng1',
                'hospital (t)': 'yi1yuan4',
                'supermarket (t)': 'chao1shi4',
                'store, shop (t)': 'shan1dian4',
                'psychologist': 'xin li yi sheng',
                'patient': 'bing ren',
                'director': 'yuan zhang',
                'she came to Hungary to study psychology': 'ta lai xiong ya li xue xin li xue',
                'allergy': 'guo min',
                'bird': 'niao',
                'colour': 'yan se',
                'it is white color': 'shi bai se de',
                'black': 'hei se',
                'brown': 'zong se',
                'yellow': 'huang se',
                'red': 'hong se',
                'blue': 'lan se',
                'green': 'lu se',
                'pink': 'fen se',
                'purple': 'zi se',
                'bright': 'liang',
                'quiet': 'anjing',
                'ski': 'tian kong',
                'warm': 'nuan',
                'hot': 're',
                'burning hot': 'tang',
                'pet': 'chong wu'
                }

chinese_0926 = {'chinese language (t)': 'han4yu3',
                'korean language (t)': 'han2yu3',
                'I hope you can taste it': "wo qing nimen chang yi chang",
                'hope (t)': 'xi1wang4',
                'wash dishes (t)': 'xi1wan3',
                'health (t)': 'shen1ti3',
                'first time': 'di yi ci',
                'second time': 'di er ci',
                'to tutor (t)': 'fu2dao3',
                'I just finished tutoring': 'wo gang gang fu dao wan',
                'I tutored': 'wo fu dao le',
                'long time no see': 'hao jiu bu jien',
                'to meet': 'jian mian',
                'to remember': 'ji de',
                'to forget': 'bu ji de',
                'to remember wrong': 'ji cuo',
                'probably': 'keneng',
                'satisfied / satisfying (t)': 'man3yi4',
                'some day meet again(t)': 'gai3tian1zai4yue1',
                'to date someone': 'yue hui',
                'weekend (t)': 'zhou1mo4',
                'free time (t)': 'kong4',
                'newcomer': 'xin lai',
                'new colleagues': 'xin lai de tong shi',
                'new student': 'xin xuesheng',
                'where do you come from?': 'ni cong na lai de?',
                'I come from Hungary': 'wo cong xiong ya li',
                'study in foreign country': 'liu xue',
                'dormitory (t)': 'su4she4',
                'to rent an apartment': 'zu de gong yu',
                'to rent (t)': 'zu1',
                'rent a car': 'zu che',
                'how long? (2)': 'duo jiu/duo chang shijian?',
                'almost 5 years': 'kuai 5 nian le',
                'almost': 'kuai',
                'Im almost there': 'wo kuai dao le',
                'to arrive': 'dao',
                'concert': 'yan chang hui',
                'I take you to...': 'wo dai ni qu',
                'gate (t)': 'men2kou3',
                'near the gate': 'men kou de',
                'what a coincidence': 'hao qiao ya',
                'whatever (t)': 'sui2bian4',
                'recently (t)': 'zui4jing4',
                'the most (t)': 'zui4',
                'close (t)': 'jing4',
                'with (t)': 'gen',
                'I still...': 'wo hai...'
                }

chinese_1003 = {'cold (sickness) (t)': 'gan3mao4',
                'running nose (t)': 'liu2 bi2ti',
                'coughing (t)': 'ke2sou4',
                'fever (t)': 'fa1shao1',
                'temperature (t)': 'ti3wen1',
                'normal (t)': 'zheng4chang2',
                'have to (t)': 'yi2ding4',
                'must (t)': 'bi4xu1',
                'need (t)': 'xu1yao4',
                'need (more polite, spoken) (t)': 'yong4',
                'can - the ability to do something (t)': 'neng2',
                'may, can - (very polite) (t)': 'ke3yi3',
                'inherently know to do / will do something (t)': 'hui4',
                'hobby (t)': 'ai4hao4',
                'I finished the relationship with her': 'wo he tai de guan xi duan le',
                'to know somebody well (t)': 'liao2jie3',
                'to make an appointment (t)': 'yue1hao3',
                "what's up?": 'ni you shenme shi ma?',
                'to invite (t)': 'qing1',
                'some (t)': 'yi4xie1',
                'to hope, to wish (t)': 'xi1wang4',
                'you first come to my house': 'ni xian lai wo jia',
                'first (t)': 'xian1',
                'then': 'hou',
                'I finish my class, then I can help you': 'wo xian shangke, xia ke hou wo keyi ban ni',
                'small restaurant (t) 1': 'can1guan3',
                'small restaurant (t) 2': 'fan4guan3',
                'swimming pool': 'you yong guan',
                'early morning': 'zaoshang',
                'délelőtt': 'shang wu',
                'dél': 'zhong wu',
                'afternoon': 'xia wu',
                'evening': 'wan shang',
                "to think (3)": 'kan / ren wei / jue de',
                'what do you think?': 'ni kan xing ma?',
                'ok (t)': 'xing2',
                'persze (t)': 'dang1ran2',
                'week (2)': 'zhou / xing qi',
                'to leave, set out': 'chu fa',
                'what are you doing?': 'mang zhe ne?',
                '...ing': 'zhe',
                'Im writing an essay': 'wo zai mang zhe xie lun wen',
                'I stil have some things I havent finished writing': 'hai you yi dian dong xi mei xie wan',
                'I havent finished work yet': 'wo mei gong zou wan',
                'often': 'jing chang',
                'work overtime': 'jia ban',
                'personally will': 'hui',
                'have to will': 'yao',
                'how about?': 'yao bu',
                'go shopping': 'qu guang jie',
                'approximately (t)': 'da4gai4',
                'a little bit later': 'wan yi dian',
                'no rush': 'bie zhao ji'}

chinese_1005 = {'happy (in life) (t)': 'xin1fu2',
                'sad': 'bei shang',
                'or - only in question sentence': 'hai shi',
                'or - selective in normal sentence (t)': 'hou4zhe3',
                'normally': 'yi ban laishuo',
                'I work from 9 to 6': 'cong 9 dian dao 6 dian gongzuo',
                'bacon': 'pei gen',
                'ham': "huo tui",
                'too heavy (food)': 'tai ni le',
                'some people say': 'you ren shuo',
                'shui bu zhao (jiao)': 'cannot fall asleep',
                'for example': 'bi ru',
                'should': 'yin gai',
                'you should look after your mom': 'ni ying gai zhao gu ni de mama',
                'call takeaway food': 'jiao wai mai',
                'order food': 'dian cai',
                'rarely': 'shao zuo',
                'prefer': 'geng xihuan',
                'get used to': 'xi guan',
                'compared to Chinese food, I prefer Hungarian food':
                    'bi qi zhong guo cai, wo geng xihuan xiong ya li cai',
                'recently': 'zuijing',
                'very, especially (t)': 'te4bie2',
                'wake up': 'xing le',
                'lie down for a while': 'tang yi hui er',
                'have to (less strong then bi xu)': 'jiu dei',
                'feed the cat': 'wei mao',
                'I feed the cat (ba structure)': 'ba mao wei le',
                'before 8': '8 dian zhi qian / yi qian',
                'after 8': '8 dian zhi hou / yi hou',
                'lunch': 'wu fan',
                'definitely (2)': 'keng ding / yi ding',
                'I cannot read characters (2)': 'wo bu hui du/nian hanzi',
                'to write (t)': 'xie3',
                '5 in the afternoon I finish work': 'xia wu wu dian xia ban',
                'after going home': 'hui jia zhi hou',
                'gym': 'jian shen feng',
                'training': 'duan lian',
                'one week two times for one hour': 'yi zhou liang ci, yi ge xiao shi',
                'to do sports': 'yun dong',
                'about (lit: left right)': 'zuo you',
                'about 3 hours': '3 xiao shi zuo you',
                'to relax': 'fang song',
                'again': 'zai',
                'first': 'xian',
                'stay at home': 'dai jia li',
                'listen to music': 'ting yin yue',
                'romantic movie': 'ai qing pian',
                'literary movie (fiction, novels)': 'wen yi pian',
                'travel (t)': 'liü3xing2',
                'have been to': 'qu guo',
                'have you been to China before?': 'ni qu guo zhong guo ma?',
                'like (giving example)': 'xiang',
                'go abroad': 'qu guo bie de guo jia',
                'other (2)': 'bie de/ qi ta de',
                'country': 'guo jia',
                'how many countries are there?': 'you duo shao guo jia?',
                'dance class': 'wu dao ke',
                'to dance': 'tao wu',
                'next time when we have another chance lets go together': 'xia ci you ji hui women zai qu ba',
                'opportunity': 'jihui'
                }
