first_word_dict = {"dog": "kutya", "cat": "macska", "fish": "hal"}

chinese_0928 = {'bachelor degree (t)': 'ben3ke1',
                'master degree (t)': 'shuo4shi4',
                'sequence, one by one (t)': 'ran3hou4',
                'in that case(t)': 'na4',
                'little girl': 'xiao nu er',
                'your exact age (t)': 'zhou1sui4',
                'nominal age (t)': 'xu1sui4',
                'in my eyes': 'zai wo yan li',
                'how I see': 'zai wo kan lai',
                'to meet': 'jian mian',
                'to see': 'kan dao',
                'lady': 'nushi',
                'plus': 'ling',
                'lonely': 'gudan',
                'holiday (t)': 'fang4jia4',
                'the time when I was 25': 'wo 25 sui de shihou',
                'lively (t)': 're4nao4',
                'welcome you to my home': 'huan ying ni lai wo de jia',
                'definetely (t)': 'yi3ding4',
                'office (t)': 'ban4gong1shi4',
                'dont need to': 'bu yong qu',
                'maths (t)': 'shu4xue2',
                'number (t)': 'shu4',
                'architect': 'fan zi she ji shi',
                'doctor (t)': 'yi1sheng1',
                'hospital (t)': 'yi1yuan4',
                'supermarket (t)': 'chao1shi4',
                'store, shop (t)': 'shan1dian4',
                'psychologist': 'xin li yi sheng',
                'patient': 'bing ren',
                'director': 'yuan zhang',
                'she came to Hungary to study psychology': 'ta lai xiong ya li xue xin li xue',
                'allergy': 'guo min',
                'bird': 'niao',
                'colour': 'yan se',
                'it is white color': 'shi bai se de',
                'black': 'hei se',
                'brown': 'zong se',
                'yellow': 'huang se',
                'red': 'hong se',
                'blue': 'lan se',
                'green': 'lu se',
                'pink': 'fen se',
                'purple': 'zi se',
                'bright': 'liang',
                'quiet': 'anjing',
                'ski': 'tian kong',
                'warm': 'nuan',
                'hot': 're',
                'burning hot': 'tang',
                'pet': 'chong wu'
                }

chinese_0926 = {'chinese language (t)': 'han4yu3',
                'korean language (t)': 'han2yu3',
                'I hope you can taste it': "wo qing nimen chang yi chang",
                'hope (t)': 'xi1wang4',
                'wash dishes (t)': 'xi1wan3',
                'health (t)': 'shen1ti3',
                'first time': 'di yi ci',
                'second time': 'di er ci',
                'to tutor (t)': 'fu2dao3',
                'I just finished tutoring': 'wo gang gang fu dao wan',
                'I tutored': 'wo fu dao le',
                }

chinese_1003 = {'cold (sickness) (t)': 'gan3mao4',
                'running nose (t)': 'liu2 bi2ti',
                'coughing (t)': 'ke2sou4',
                'fever (t)': 'fa1shao1',
                'temperature (t)': 'ti3wen1',
                'normal (t)': 'zheng4chang2',
                'have to (t)': 'yi2ding4',
                'must (t)': 'bi4xu1',
                'need (t)': 'xu1yao4',
                'need (more polite, spoken) (t)': 'yong4',
                'can - the ability to do something (t)': 'neng2',
                'may, can - (very polite) (t)': 'ke3yi3',
                'inherently know to do / will do something (t)': 'hui4',
                'hobby (t)': 'ai4hao4',
                'I finished the relationship with her': 'wo he tai de guan xi duan le',
                'to know somebody well (t)': 'liao2jie3',
                'to make an appointment (t)': 'yue1hao3',
                "what's up?": 'ni you shenme shi ma?',
                'to invite (t)': 'qing1',
                'some (t)': 'yi4xie1',
                'to hope, to wish (t)': 'xi1wang4',
                'you first come to my house': 'ni xian lai wo jia',
                'first (t)': 'xian1',
                'then': 'hou',
                'I finish my class, then I can help you': 'wo xian shangke, xia ke hou wo keyi ban ni',
                'small restaurant (t) 1': 'can1guan3',
                'small restaurant (t) 2': 'fan4guan3',
                'swimming pool': 'you yong guan',
                'early morning': 'zaoshang',
                'délelőtt': 'shang wu',
                'dél': 'zhong wu',
                'afternoon': 'xia wu',
                'evening': 'wan shang',
                "to think (3)": 'kan / ren wei / jue de',
                'what do you think?': 'ni kan xing ma?',
                'ok (t)': 'xing2',
                'persze (t)': 'dang1ran2',
                'week (2)': 'zhou / xing qi',
                'to leave, set out': 'chu fa',
                'what are you doing?': 'mang zhe ne?',
                '...ing': 'zhe',
                'Im writing an essay': 'wo zai mang zhe xie lun wen',
                'I stil have some things I havent finished writing': 'hai you yi dian dong xi mei xie wan',
                'I havent finished work yet': 'wo mei gong zou wan',
                'often': 'jing chang',
                'work overtime': 'jia ban',
                'personally will': 'hui',
                'have to will': 'yao',
                'how about?': 'yao bu',
                'go shopping': 'qu guang jie',
                'approximately': 'da gai',
                'a little bit later': 'wan yi dian',
                'no rush': 'bie zhao ji'}

chinese_1005 = {'happy (in life) (t)': 'xin1fu2',
                'sad': 'bei shang',
                'or - only in question sentence': 'hai shi',
                'or - selective in normal sentence (t)': 'hou4zhe3',
                'normally': 'yi ban laishuo',
                'I work from 9 to 6': 'cong 9 dian dao 6 dian gongzuo',
                'bacon': 'pei gen',
                'ham': "huo tui",
                'too heavy (food)': 'tai ni le',
                'some people say': 'you ren shuo',
                'shui bu zhao (jiao)': 'cannot fall asleep',
                'for example': 'bi ru',
                'should': 'yin gai',
                'you should look after your mom': 'ni ying gai zhao gu ni de mama',
                'call takeaway food': 'jiao wai mai',
                'order food': 'dian cai',
                'rarely': 'shao zuo',
                'prefer': 'geng xihuan',
                'get used to': 'xi guan',
                'compared to Chinese food, I prefer Hungarian food':
                    'bi qi zhong guo cai, wo geng xihuan xiong ya li cai',
                }
